# Generated by Django 5.2.4 on 2025-07-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input_testcase',
            field=models.FileField(default='testcases/default.txt', upload_to='testcases/'),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_testcase',
            field=models.FileField(default='testcases/default.txt', upload_to='testcases/'),
        ),
    ]
