# Generated by Django 5.2.4 on 2025-07-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_input_testcase_problem_output_testcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='input_testcase',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='output_testcase',
        ),
    ]
